language: python
python:
  - "2.7"
  - "pypy"
  - "3.3"
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install coveralls
  - pip install normalizer
script: make travis
after_success: coveralls
notifications:
  email:
    - silpa-discuss@nongnu.org
  irc:
    channels:
      - 'irc.freenode.net#silpa'
    on_success: change
    on_failure: change
    use_notice: true
